#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service 03-monitoring
SERVICE_NAME="memcached"

check_container_initialized
liftoff

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- memcached "$@"
fi

create_zabbix memcached

liftoff

print_start "Starting Memcached ${MEMCACHED_VERSION}"
exec s6-setuidgid memcached memcached
