#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="memcached"

check_container_initialized
liftoff

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- memcached "$@"
fi

liftoff

print_start "Starting Memcached ${MEMCACHED_VERSION}"
exec s6-setuidgid memcached memcached
