#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="memcached"

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- memcached "$@"
fi

liftoff

print info "Startint Memcached ${MEMCACHED_VERSION}"
exec s6-setuidgid memcache memcached

