#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="memcached"

check_container_initialized
liftoff

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- memcached "$@"
fi

liftoff

print info "Startint Memcached ${MEMCACHED_VERSION}"
exec s6-setuidgid memcache memcached
