version: '3.7'
services:
  
  memcached-app:
    image: tiredofit/memcached
    container_name: memcached-app
    environment: 
      - ZABBIX_HOSTNAME=memcached-app
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true


